In [1]:
import seaborn as sn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
transactions = pd.read_csv(r"C:\Users\JONATHAN GEORGE\Downloads\PS_20174392719_1491204439457_log.csv")

In [3]:
print(transactions.head())
print(transactions.info())

   step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 co

In [4]:
# Number of unique values in 'your_column'
unique_values_count = transactions['isFraud'].nunique()

# Print the result
print(f"Number of unique attributes in 'isFraud': {unique_values_count}")


Number of unique attributes in 'isFraud': 2


In [5]:
# Count of each unique value in 'your_column'
value_counts = transactions['isFraud'].value_counts()

# Print the result
print("Count of each unique value in 'isFraud':")
print(value_counts)

Count of each unique value in 'isFraud':
isFraud
0    6354407
1       8213
Name: count, dtype: int64


In [6]:
# we have 8,213 fraudulent transactions in this data

In [7]:
transactions['amount'].describe()

count    6.362620e+06
mean     1.798619e+05
std      6.038582e+05
min      0.000000e+00
25%      1.338957e+04
50%      7.487194e+04
75%      2.087215e+05
max      9.244552e+07
Name: amount, dtype: float64

In [8]:
# Create the 'isPayment' column using apply with a lambda function
transactions['isPayment'] = transactions['type'].apply(lambda x: 1 if x in ['PAYMENT', 'DEBIT'] else 0)

# Display the DataFrame
print(transactions)

         step      type      amount     nameOrig  oldbalanceOrg  \
0           1   PAYMENT     9839.64  C1231006815      170136.00   
1           1   PAYMENT     1864.28  C1666544295       21249.00   
2           1  TRANSFER      181.00  C1305486145         181.00   
3           1  CASH_OUT      181.00   C840083671         181.00   
4           1   PAYMENT    11668.14  C2048537720       41554.00   
...       ...       ...         ...          ...            ...   
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0             160296.36  M1979787155            0.00            0.00        0   
1              19384.72  M2044282

In [9]:
# Create the 'isMovement' column using apply with a lambda function
transactions['isMovement'] = transactions['type'].apply(lambda x: 1 if x in ['CASH_OUT', 'TRANSFER'] else 0)

# Display the DataFrame
print(transactions)

         step      type      amount     nameOrig  oldbalanceOrg  \
0           1   PAYMENT     9839.64  C1231006815      170136.00   
1           1   PAYMENT     1864.28  C1666544295       21249.00   
2           1  TRANSFER      181.00  C1305486145         181.00   
3           1  CASH_OUT      181.00   C840083671         181.00   
4           1   PAYMENT    11668.14  C2048537720       41554.00   
...       ...       ...         ...          ...            ...   
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0             160296.36  M1979787155            0.00            0.00        0   
1              19384.72  M2044282

In [10]:
# Create the 'accountDiff' column with the absolute difference
transactions['accountDiff'] = (transactions['oldbalanceOrg'] - transactions['oldbalanceDest']).abs()

# Display the DataFrame
print(transactions)

         step      type      amount     nameOrig  oldbalanceOrg  \
0           1   PAYMENT     9839.64  C1231006815      170136.00   
1           1   PAYMENT     1864.28  C1666544295       21249.00   
2           1  TRANSFER      181.00  C1305486145         181.00   
3           1  CASH_OUT      181.00   C840083671         181.00   
4           1   PAYMENT    11668.14  C2048537720       41554.00   
...       ...       ...         ...          ...            ...   
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0             160296.36  M1979787155            0.00            0.00        0   
1              19384.72  M2044282

In [11]:
# Create the features array with the specified columns
features = transactions[['amount', 'isPayment', 'isMovement', 'accountDiff']].values

In [12]:
# Create the label variable with the 'isFraud' column
label = transactions['isFraud'].values


In [13]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.3, random_state=42)

In [14]:
# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the training features and transform them
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test features
X_test_scaled = scaler.transform(X_test)

In [15]:
# Create a LogisticRegression model
model = LogisticRegression(random_state=42)

In [16]:
# Fit the model on the training data
model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [17]:
# Print the coefficients of the model
print("Coefficients of the logistic regression model:")
print(model.coef_)

Coefficients of the logistic regression model:
[[ 0.22175467 -1.17122122  3.58888713 -0.66133785]]


In [18]:
# Print the intercept of the model
print("Intercept of the logistic regression model:")
print(model.intercept_)

Intercept of the logistic regression model:
[-10.91244106]


In [19]:
# Predict the labels for the test set
y_pred = model.predict(X_test_scaled)

In [20]:
# Display the predictions
print("Predictions on the test set:")
print(y_pred)

Predictions on the test set:
[0 0 0 ... 0 0 0]


In [21]:
# Evaluate the model on the training data
training_score = model.score(X_train_scaled, y_train)

In [22]:
# Print the training score
print("Training accuracy score of the logistic regression model:")
print(training_score)

Training accuracy score of the logistic regression model:
0.9986829325026483


In [23]:
# Evaluate the model on the test data
test_score = model.score(X_test_scaled, y_test)

In [24]:
# Print the test score
print("Test accuracy score of the logistic regression model:")
print(test_score)

Test accuracy score of the logistic regression model:
0.9987017926577416


In [25]:
# Get the feature names
feature_names = ['amount', 'isPayment', 'isMovement', 'accountDiff']

In [26]:
# Create a DataFrame to display the coefficients
coefficients_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': model.coef_[0]})

In [27]:
# Print the coefficients DataFrame
print("Coefficients for the logistic regression model:")
print(coefficients_df)

Coefficients for the logistic regression model:
       Feature  Coefficient
0       amount     0.221755
1    isPayment    -1.171221
2   isMovement     3.588887
3  accountDiff    -0.661338


In [28]:
# the most important feature was isMovement

In [29]:
# Given transaction arrays
transaction1 = np.array([123456.78, 0.0, 1.0, 54670.1])
transaction2 = np.array([98765.43, 1.0, 0.0, 8524.75])
transaction3 = np.array([543678.31, 1.0, 0.0, 510025.5])
your_transaction = np.array([190656, 1.0, 0.0, 21116])

# Combine the transaction arrays into a single numpy array
sample_transactions = np.vstack([transaction1, transaction2, transaction3, your_transaction])

In [30]:
# Display the combined array
print("Combined sample transactions:")
print(sample_transactions)

Combined sample transactions:
[[1.2345678e+05 0.0000000e+00 1.0000000e+00 5.4670100e+04]
 [9.8765430e+04 1.0000000e+00 0.0000000e+00 8.5247500e+03]
 [5.4367831e+05 1.0000000e+00 0.0000000e+00 5.1002550e+05]
 [1.9065600e+05 1.0000000e+00 0.0000000e+00 2.1116000e+04]]


In [31]:
# Apply the StandardScaler object's transform method to sample_transactions
sample_transactions = scaler.transform(sample_transactions)

In [32]:
# Display the transformed sample_transactions
print("Transformed sample transactions:")
print(sample_transactions)

Transformed sample transactions:
[[-0.09356    -0.7250953   1.13831764 -0.37416411]
 [-0.13455025  1.37912905 -0.87848942 -0.38561603]
 [ 0.60405216  1.37912905 -0.87848942 -0.26115821]
 [ 0.01799781  1.37912905 -0.87848942 -0.38249125]]


In [33]:
# Use the model's predict method on sample_transactions
fraudulent_transactions = model.predict(sample_transactions)

In [34]:
# Print the result
print("Predicted fraudulent transactions:")
print(fraudulent_transactions)

Predicted fraudulent transactions:
[0 0 0 0]


In [35]:
# Use the model's predict_proba method on sample_transactions
transaction_probabilities = model.predict_proba(sample_transactions)

In [36]:
# Print the result
print("Probabilities for each transaction:")
print(transaction_probabilities)

Probabilities for each transaction:
[[9.96831107e-01 3.16889315e-03]
 [9.99999806e-01 1.94016916e-07]
 [9.99999790e-01 2.10487274e-07]
 [9.99999800e-01 2.00278131e-07]]
